### ISSUE TITLE
17.2.3 생성자 함수의 인스턴스 생성 과정 오탈자

### ISSUE THREAD

**Issue by myeongseoklee** [wikibook/mjs#7]
239페이지
1. 인스턴스 생성과 this 바인딩
암묵적으로 빈 객체가 생성된다. ~~ 이 처리는 함수 몸체의 코드가 한 줄씩 실행되는 **_런타임 이전에_** 실행된다.

소제목 설명하는 문단의 마지막 부분의 "런타임 이전"이 맞는 정보인가요?
빈 객체(인스턴스)가 생성되고 this 바인딩 되는 시점은 인스턴스를 생성하는 런타임 아닌가요?

**Comment by wikibook** [comment]
@myeongseoklee 님, 안녕하세요.
위키북스 담당자입니다.

제보해 주신 내용을 저자분께 전달해 드렸고, 아래와 같은 답신을 받았습니다.

> 함수를 호출하면 함수 코드가 한 줄씩 실행되는 런타임 이전에 빈 객체가 생성되어 this에 바인딩됩니다.

참고 부탁드리고요, 오늘도 편안하고 즐거운 하루 보내세요..!
고맙습니다.
